### ISSUE TITLE
Comparative experiments

### ISSUE THREAD

**Issue by heeta0** [Masaaki-75/freeseed#1]
Hello, In your freeseed article, I found that the comparison experiment DuDoTrans reached about 43 PSNR, and in the official code of DuDoTrans, I reproduced only about 35 PSNR, I would like to know how you achieved the effect improvement. 

Looking forward to your reply, thank you

**Comment by Masaaki-75** [comment]
I did encouter similar issue during reproduction, and this seems to require some tricks. One transformer is already more difficult to converge than a CNN, let alone now having two ( the two are even in different domains!)... So I suggest using pre-trained checkpoints (either from SwinIR or the official DuDoTrans page) to accelerate this process. Also, in [DuDoTrans](https://github.com/mars11121/DuDoTrans/blob/main/main.py#L44) they used two individual optimizers, which is a bit different from typical training CNNs like FBPConvNet.

For more effective solutions, it may be better to contact authors of DuDoTrans?

**Comment by heeta0** [comment]
> 我在复制过程中确实遇到了类似的问题，这似乎需要一些技巧。一个变压器已经比 CNN 更难收敛了，更不用说现在有两个（两者甚至在不同的领域！...因此，我建议使用预先训练的检查点（来自 SwinIR 或 DuDoTrans 官方页面）来加速此过程。此外，在 [DuDoTrans](https://github.com/mars11121/DuDoTrans/blob/main/main.py#L44) 中，他们使用了两个单独的优化器，这与典型的训练 CNN （如 FBPConvNet）略有不同。
> 
> 如需更有效的解决方案，最好联系 DuDoTrans 的作者？

OK，thank you for your reply！
