### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by EvelyneCalista** [Masaaki-75/freeseed#2]
hi @Masaaki-75 ,
thanks for your great work,
I would like to run your model, however 'generate_sparse_and_gt_data' module is missing from the network class.
May I know how to produce this module?
Thank you so much

**Comment by Masaaki-75** [comment]
Hi! Thank you for your interest!

This is not a network module but a method that is used to generate simulated pair for training/evaluation. You can see its definition in every trainer class, e.g., https://github.com/Masaaki-75/freeseed/blob/6c1bd45cc5b67200e0d1a6525c89455d81296662/trainers/dudo_trainer.py#L43

**Comment by EvelyneCalista** [comment]
I got it. I solved with using this line only "sparse_mu, gt_mu = self.net.module.generate_sparse_and_full_ct(mu_ct,)" and commented "sparse_mu, gt_mu = self.net.generate_sparse_and_full_ct(mu_ct,)"

now i think there is some installation error with torch radon, it shows
"RuntimeError: CUDA error: no kernel image is available for execution on the device"
I have tried your guidance using (Updated) [Precompile](https://github.com/matteo-ronchetti/torch-radon/issues/43) Packages , but lead to another "libcufft.so.10:" error. Do you install cuda separately with pytorch before using pip install pytorch? 
[ i am using RTX 3090].

**Comment by Masaaki-75** [comment]
Yes, and in my case, I am using `Cuda compilation tools, release 11.5, V11.5.50` with `Build cuda_11.5.r11.5/compiler.30411180_0` on RTX 3090. 

If the precompiled packages do not work, I suggest building from source. This works for me when either installing torch-radon v1 or a better-maintained v2 version from https://github.com/carterbox/torch-radon. BTW, I have my walkthrough at https://github.com/Masaaki-75/proct/blob/main/inst_tr.sh. Hope that helps!

**Comment by EvelyneCalista** [comment]
Thank you so much :pleading_face: !! 
i tried your walkthrough, build from source, it shows error
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/5035d6f1-4f6c-4e05-92f1-c6b4fd3b5c18)

however your code is running with warning on torch fft
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/479ac79c-b01b-4af0-a3e1-1c7209985257)

do this condition normal? I am afraid the installation is broken somewhere

**Comment by Masaaki-75** [comment]
1. The error message on the first screenshot seems incomplete. Showing the full message may help better locate the error.
2. The warning of FFT is because there is a difference between pytorch v1.7 and higher versions in the way the FFT functions are called (the module, input arguments, etc). Calling `torch.rfft` will be deprecated in higher versions (e.g. v2.0), so pytorch is recommending using new features (e.g. `torch.fft.rfft`). However, this for now is not an error.

**Comment by EvelyneCalista** [comment]
There are 3 errors occurred, do these comes from cuda installation?
1.
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/b80cbdfc-971c-4666-9be7-fda9d4606024)

2.
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/7fc426cd-9a34-4e52-965e-082ec2555479)

3.
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/9cc930fc-045c-4c17-b61f-b2d99cdfc363)
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/14320e2f-7927-481c-a883-9a596b3c7da2)
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/c34c6172-e994-468b-ba32-2acf529611e5)

**Comment by Masaaki-75** [comment]
This indicates a build dependency problem that is more likely to stem from Linux than from cuda, and is unfortunately beyond my knowledge😟. But in the first place it seems that your linux environment did not have `cfitsio` library (a library of C and Fortran subroutines) installed properly.

**Comment by EvelyneCalista** [comment]
do you think I shall resolve the torch-radon installation for now or i can ignore it? at least the code can be run.
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/3aaff95e-f71c-4740-a64c-d4cfe09d04b3)


by the way do you again use test.sh to do same testing for validation data? i tried run test.sh to the validation data, but the result is different with the validation during training
![193_output_ct_freeseed_0 5_1_5](https://github.com/Masaaki-75/freeseed/assets/71305979/64b02866-ec34-4bc0-ad2a-0d4d0dbc6c83)
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/f1fa6aae-9c14-4e46-8880-5440f0716bbb)

**Comment by EvelyneCalista** [comment]
oh! i got it, sorry i didn't notice there are three types of weight
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/109ba1f1-d997-4e25-8526-ea98f05bc3c9)
i used the opt-seed one, after changed to net-free, it is fine.
![504_output_ct_freeseed_0 5_1_5](https://github.com/Masaaki-75/freeseed/assets/71305979/8a001d96-1c8a-4158-85c9-f899ef7d296a)
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/84570b09-3db0-4188-87ac-54ae9a275b73)

**Comment by Masaaki-75** [comment]
This is strange. Normally the code should fail without torch-radon dependency. But given that you have run the training smoothly and the visualization also looks good, we could assume the installation is okay.

**Comment by EvelyneCalista** [comment]
thank you so much for your help!

**Comment by EvelyneCalista** [comment]
hi @Masaaki-75 ,

sorry to disturb you again, I am running the dudofreenet

https://github.com/Masaaki-75/freeseed/blob/3e81152a5cd60db01c80e8404aff4c65c270ad01/wrappers/basic_wrapper_v2.py#L72C5-L84C9

this line give error
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/7c96bf17-6f0c-4abf-93ac-2b68a77b7217)
do change the line with this will be good?
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/10d00714-4fcb-4ada-adec-73ce763823ed)

but it will lead to another error with tensor mismatch
![image](https://github.com/Masaaki-75/freeseed/assets/71305979/37725444-76cb-4464-a113-9c743804abd7)

**Comment by Masaaki-75** [comment]
The bug has been fixed this afternoon, please see here: https://github.com/Masaaki-75/freeseed/commit/0e8a5d0cb327140a15038002bd7fd4c227fbb3da

I found this issue when I was confirming the test script issue you raised 😂, but forgot to notify you after fixing it. Anyway, thank you for bringing it up!

**Comment by Masaaki-75** [comment]
Also, if you are trying to load the checkpoints correctly, please do modify the default arguments in `main.py` as in https://github.com/Masaaki-75/freeseed/commit/3e81152a5cd60db01c80e8404aff4c65c270ad01.
